<?php
return [
    'mode'                     => '',
    'format'                   => 'LETTER',
    'default_font_size'        => '8',
    'default_font'             => 'Arial',
    'margin_left'              => 5,
    'margin_right'             => 5,
    'margin_top'               => 5,
    'margin_bottom'            => 5,
    'margin_header'            => 0,
    'margin_footer'            => 0,
    'orientation'              => 'P',
    'title'                    => '',
    'author'                   => '',
    'watermark'                => 'Rising Star Boarding',
    'show_watermark'           => true,
    'watermark_font'           => 'sans-serif',
    'display_mode'             => 'fullpage',
    'watermark_text_alpha'     => 0.05,
    'custom_font_dir'          => '',
    'custom_font_data'            => [],
    'auto_language_detection'  => false,
    'temp_dir'                 => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),
    'pdfa'                            => false,
    'pdfaauto'                      => false,
    'use_active_forms'         => false,
];